name: Build and push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: aj-dev-env  # Wskazanie środowiska

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        #  musisz dodać parametr distribution do akcji setup-java. Ten parametr określa, której dystrybucji JDK chcesz użyć (np. AdoptOpenJDK, Zulu, etc.).
        distribution: 'adopt' # lub 'zulu', 'temurin' itp.
        java-version: '22.0.2+9'
    
    - name: Build with Maven
      run:  mvn -f src-java/pom.xml clean package


    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker image
      run: docker build . -t xaprun/aj-java-helloapp:1.0

    - name: Push Docker image
      run: docker push xaprun/aj-java-helloapp:1.0
