name: Build and push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: aj-dev-env  # Wskazanie środowiska

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        #  musisz dodać parametr distribution do akcji setup-java. Ten parametr określa, której dystrybucji JDK chcesz użyć (np. AdoptOpenJDK, Zulu, etc.).
        distribution: 'adopt' # lub 'zulu', 'temurin' itp.
        java-version: '11'
    
    - name: Build with Maven
      run:  mvn clean package


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: file test 1
      run: pwd && ls -al && ls -al src


    - name: Build Docker image
      run: docker build . -t xaprun/aj-java-helloapp:1.0

    - name: Push Docker image
      run: docker push xaprun/aj-java-helloapp:1.0
